### ISSUE TITLE
Random decorator works weird

### ISSUE THREAD

**Issue by camilonova** [skoczen/will#119]
Hi there,

I was trying to use a function like:

```
    @randomly(start_hour='9', end_hour='16', day_of_week="mon-fri", num_times_per_day=2)
    def hold_my_beer(self):
```

And I was getting this errors:

```
2015-03-31T05:00:00.858058+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
2015-03-31T05:00:00.814868+00:00 app[web.1]: Process Process-3:
2015-03-31T05:00:00.839808+00:00 app[web.1]: Traceback (most recent call last):
2015-03-31T05:00:00.896373+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/multiprocessing/process.py", line 114, in run
2015-03-31T05:00:00.896359+00:00 app[web.1]:     self.run()
2015-03-31T05:00:00.896412+00:00 app[web.1]:     self._target(*self._args, **self._kwargs)
2015-03-31T05:00:00.896437+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/will/main.py", line 306, in bootstrap_scheduler
2015-03-31T05:00:00.896818+00:00 app[web.1]:     self.scheduler.start_loop(self)
2015-03-31T05:00:00.896839+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/will/scheduler.py", line 30, in start_loop
2015-03-31T05:00:00.896980+00:00 app[web.1]:     self.check_scheduled_actions()
2015-03-31T05:00:00.897003+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/will/scheduler.py", line 102, in check_scheduled_actions
2015-03-31T05:00:00.897031+00:00 app[web.1]:     fn.start_hour,
2015-03-31T05:00:00.907116+00:00 app[web.1]: AttributeError: 'function' object has no attribute 'start_hour'
```

Then I renamed the function as:

```
    @randomly(start_hour='9', end_hour='16', day_of_week="mon-fri", num_times_per_day=2)
    def holdmybeer(self):
```

And now is working fine.

Can you check how are you decorating or calling the function?

PS: This was so hard to debug

**Comment by camilonova** [comment]
Correction, is not working.

```
2015-04-01T05:00:00.127330+00:00 app[web.1]: Traceback (most recent call last):
2015-04-01T05:00:00.127255+00:00 app[web.1]: Process Process-3:
2015-04-01T05:00:00.133843+00:00 app[web.1]:     self.run()
2015-04-01T05:00:00.147066+00:00 app[web.1]:     self.scheduler.start_loop(self)
2015-04-01T05:00:00.147072+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/will/scheduler.py", line 30, in start_loop
2015-04-01T05:00:00.154660+00:00 app[web.1]:     self.check_scheduled_actions()
2015-04-01T05:00:00.127463+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
2015-04-01T05:00:00.154683+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/will/scheduler.py", line 102, in check_scheduled_actions
2015-04-01T05:00:00.133849+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/multiprocessing/process.py", line 114, in run
2015-04-01T05:00:00.133883+00:00 app[web.1]:     self._target(*self._args, **self._kwargs)
2015-04-01T05:00:00.154742+00:00 app[web.1]:     fn.start_hour,
2015-04-01T05:00:00.133910+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/will/main.py", line 306, in bootstrap_scheduler
2015-04-01T05:00:00.154772+00:00 app[web.1]: AttributeError: 'function' object has no attribute 'start_hour'
2015-04-01T06:01:23.042715+00:00 heroku[web.1]: Idling
2015-04-01T06:01:23.043166+00:00 heroku[web.1]: State changed from up to down
2015-04-01T06:01:25.474748+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2015-04-01T06:01:26.877484+00:00 heroku[web.1]: Process exited with status 143
```

**Comment by skoczen** [comment]
Hey @camilonova ,

Yep, that looks like a bug - actually introduced in a refactor a bit ago - will aim to get a fix out to you this week.

Thanks for raising & documenting it here, and for your patience as it gets fixed!

-Steven

**Comment by camilonova** [comment]
I'll wait for it. Thanks

**Comment by camilonova** [comment]
@skoczen any updates?

**Comment by skoczen** [comment]
@camilonova  
Sure thing - since last we talked, I moved to Mexico. :)  Probably not the update you were looking for, but know this is still on my radar.  My open-source projects come after work and a couple of projects, but it will get done.

Thanks for your patience!

-Steven

**Comment by camilonova** [comment]
Way to go @skoczen :beers: 

![lshmsfoaidmt_2d2dc5_2453677](https://cloud.githubusercontent.com/assets/202559/7050377/a169fe0a-dde6-11e4-8d64-56a2ee5f6605.jpg)

**Comment by camilonova** [comment]
@skoczen I just realized somehow the tasks is still registered and executed after I removed the code, if I try to enable the task again it will break, and removing it somehow works but this is completely unexpected behavior.

If you don't have enough time right now you can tell me where to look, or what commits should I see to try to fix this on my own.

Thanks.

**Comment by skoczen** [comment]
Actually have a block of time today, hoping to get this + lots of other stuff out!  Will update here when it's released.

**Comment by skoczen** [comment]
This is fixed, and released (with a bunch of other stuff) in v[0.8](http://skoczen.github.io/will/improve/#releases)!

**Comment by camilonova** [comment]
Thank you very much

**Comment by camilonova** [comment]
@skoczen just get this:

```
2015-04-24T05:00:00.920541+00:00 app[web.1]: Traceback (most recent call last):
2015-04-24T05:00:00.920593+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
2015-04-24T05:00:00.926630+00:00 app[web.1]:     self.run()
2015-04-24T05:00:00.926635+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/multiprocessing/process.py", line 114, in run
2015-04-24T05:00:00.926669+00:00 app[web.1]:     self._target(*self._args, **self._kwargs)
2015-04-24T05:00:00.944312+00:00 app[web.1]:     self.scheduler.start_loop(self)
2015-04-24T05:00:00.926713+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/will/main.py", line 337, in bootstrap_scheduler
2015-04-24T05:00:00.944333+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/will/scheduler.py", line 30, in start_loop
2015-04-24T05:00:00.970309+00:00 app[web.1]:     self.check_scheduled_actions()
2015-04-24T05:00:00.970359+00:00 app[web.1]:     meta.start_hour,
2015-04-24T05:00:00.970317+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/will/scheduler.py", line 103, in check_scheduled_actions
2015-04-24T05:00:00.977163+00:00 app[web.1]: AttributeError: 'dict' object has no attribute 'start_hour'
2015-04-24T05:00:00.909076+00:00 app[web.1]: Process Process-3:
2015-04-24T06:01:35.216235+00:00 heroku[web.1]: Idling
2015-04-24T06:01:35.217112+00:00 heroku[web.1]: State changed from up to down
2015-04-24T06:01:38.007347+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2015-04-24T06:01:39.615435+00:00 heroku[web.1]: Process exited with status 143
```

This is my decorator:

```
    @randomly(
        start_hour='9',
        end_hour='16',
        day_of_week="mon-fri",
        num_times_per_day=2,
    )
    def holdmybeer(self):
```

**Comment by skoczen** [comment]
So, I have a fix that should take care of the error you're seeing, **but** - randomlys were working here, without it.  When use your exact code here on 0.8.1, I don't get any errors, even before my changes.  Which worries me.

Can you provide more details on your setup?  Python runtime (2.7.something, looks like), etc?

I've also pushed that change to master, so you can test it out.

```bash
pip install -e git+https://github.com/skoczen/will#egg=will
```

Let me know how it goes!

**Comment by skoczen** [comment]
@camilonova ^ 

(In case you don't get thread pings)

**Comment by camilonova** [comment]
@skoczen seems is working fine now with master.

**Comment by skoczen** [comment]
Weird.  Ok, well, it's no harm, works here as well - will get a release out shortly!

**Comment by skoczen** [comment]
@camilonova released and out as 0.8.2!

**Comment by camilonova** [comment]
Thank you, if I find more issues I'll open a new ticket.

**Comment by skoczen** [comment]
Please do - thanks for all your help & patience on this!
