### ISSUE TITLE
self.save a Message object?

### ISSUE THREAD

**Issue by brandonsturgeon** [skoczen/will#141]
I want to be able to save a message object so I can reply to it later/elsewhere. I get this error when trying `self.save("the_message", message)`
```
CRITICAL Unable to save the_message:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/will/mixins/storage.py", line 41, in save
    ret = self.storage.set(key, pickle.dumps(value))
  File "/usr/lib/python2.7/site-packages/dill/dill.py", line 143, in dumps
    dump(obj, file, protocol, byref)
  File "/usr/lib/python2.7/site-packages/dill/dill.py", line 136, in dump
    pik.dump(obj)
  File "/usr/lib64/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib64/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib64/python2.7/pickle.py", line 419, in save_reduce
    save(state)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/site-packages/dill/dill.py", line 504, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib64/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib64/python2.7/pickle.py", line 681, in _batch_setitems
    save(v)
  File "/usr/lib64/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib64/python2.7/pickle.py", line 400, in save_reduce
    save(func)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/site-packages/dill/dill.py", line 461, in save_function
    if not _locate_function(obj): #, pickler._session):
  File "/usr/lib/python2.7/site-packages/dill/dill.py", line 450, in _locate_function
    found = _import_module(obj.__module__ + '.' + obj.__name__, safe=True)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'`
```
Looks like `obj` is missing either `__module__` or  `__name__` (likely both)

So, if I'm unable to save a message object, is there any way I can extract specific info from the message and then sort of re-build the message when I need to reply to it? Keep in mind I want this to work inside rooms and 1-1 chats. 

EDIT: I came up with a solution. I checked if the message was a room or a 1-1 chat. Then I just saved the ID of the message (room_id for rooms, hipchat_id for 1-1 chat) and saved the ID instead of the whole object.

**Comment by skoczen** [comment]
Hey @brandonsturgeon 

Awesome, that was going to be my advice.  `self.save()` can save *almost* anything, but things get complicated when the object in question is tied to network resources, callbacks, threads, or async stuff.   

Pulling out the attributes you need to save will always work, and will be faster, to boot.

Glad you got it solved!

-Steven
