### ISSUE TITLE
Bug when upgrade to 0.9.1

### ISSUE THREAD

**Issue by camilonova** [skoczen/will#158]
I got this just after upgrading:

```
2015-06-05T15:34:55.414341+00:00 app[web.1]: CRITICAL Error bootstrapping xmpp:
2015-06-05T15:34:55.414348+00:00 app[web.1]:
2015-06-05T15:34:55.414350+00:00 app[web.1]: Traceback (most recent call last):
2015-06-05T15:34:55.414352+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/will/main.py", line 372, in bootstrap_xmpp
2015-06-05T15:34:55.414354+00:00 app[web.1]:     self.start_xmpp_client()
2015-06-05T15:34:55.414355+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/will/listener.py", line 32, in start_xmpp_client
2015-06-05T15:34:55.414358+00:00 app[web.1]: TypeError: 'NoneType' object is not iterable
2015-06-05T15:34:55.414357+00:00 app[web.1]:     for r in settings.ROOMS:
2015-06-05T15:34:55.414360+00:00 app[web.1]:
2015-06-05T15:34:55.414362+00:00 app[web.1]: Continuing...
2015-06-05T15:34:55.414363+00:00 app[web.1]:
2015-06-05T15:34:55.471877+00:00 app[web.1]:   ✓ Scheduler started.
```

Seems settings.ROOMS is None, I don't have it on my config file, because I want to join all rooms.

I was checking at the source code, and I didn't understand what does this line https://github.com/skoczen/will/blob/master/will/listener.py#L31

**Comment by skoczen** [comment]
Hey @camilonova , 

Weird.  I don't remember anything changing around there, but I'm trying to replicate now.

The line you point out is a gross hack where I'm using a property like an init function.  The comment above refers to it.  Definitely not pretty.

**Comment by skoczen** [comment]
Yep. Verified here.  And I know what's causing it.  Unfortunately, it's not an easy fix.  Will see what I can do shortly!

**Comment by skoczen** [comment]
@camilonova found and fixed (turns out to just have been a bad merge), and released as [0.9.2](http://skoczen.github.io/will/improve/#releases).  That fixed it here, please close if it takes care of you as well.

Thanks for the quick and accurate report!

**Comment by camilonova** [comment]
@skoczen Thank you so much, works like charm

**Comment by skoczen** [comment]
Glad to hear it - thanks for your patience and help getting it fixed!
