### ISSUE TITLE
Error when verifying user credentials

### ISSUE THREAD

**Issue by deeplook** [skoczen/will#219]
I'm getting this traceback now every time I'm trying to run Will 0.9.3, and it's not obvious to me how to debug this. I've probably just installed a few more packages before Will broke. Any suggestions of where to look? Thanks!

```python
$ ~/miniconda/bin/python run_will.py
[...]
Verifying credentials...
Process Process-1:
Traceback (most recent call last):
  File "/Users/dinu/miniconda/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/dinu/miniconda/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/dinu/miniconda/lib/python2.7/site-packages/will/mixins/hipchat.py", line 91, in get_hipchat_user
    q.put(r.json())
  File "/Users/dinu/miniconda/lib/python2.7/site-packages/requests/models.py", line 776, in json
    return json.loads(self.text, **kwargs)
  File "/Users/dinu/miniconda/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Users/dinu/miniconda/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/dinu/miniconda/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

```

**Comment by woohgit** [comment]
Maybe you tried to run will at wrong time. HipChat servers were down yesterday for about 2-3 hours. :) Can you retry it now? Is it still an issue?

**Comment by deeplook** [comment]
Indeed, now it's working nicely, again. A great bug fix! ;-)
