### ISSUE TITLE
Will will not run on Windows

### ISSUE THREAD

**Issue by FireDrunk** [skoczen/will#245]
Been trying to get Will to run on Windows. I'm aware of the hiredis package errors on Windows, but i'm using local storage so, i shouldn't need any redis packages to get this working. I've installed all other requirements except hiredis. 
```
pip install -r requirements.txt

Requirement already satisfied (use --upgrade to upgrade): bottle==0.12.7 in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): clint==0.3.7 in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): dill==0.2.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): dnspython==1.12.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): natural==0.1.5 in c:\python27\lib\site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): requests==2.4.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): parsedatetime==1.1.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): pyasn1==0.1.7 in c:\python27\lib\site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): pyasn1-modules==0.0.5 in c:\python27\lib\site-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): sleekxmpp==1.3.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): APScheduler==2.1.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): CherryPy==3.6.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.7.3 in c:\python27\lib\site-packages (from -r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): Markdown==2.3.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.23 in c:\python27\lib\site-packages (from -r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): PyYAML==3.10 in c:\python27\lib\site-packages (from -r requirements.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): pygerduty==0.28 in c:\python27\lib\site-packages (from -r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): args in c:\python27\lib\site-packages (from clint==0.3.7->-r requirements.txt (line 2))
Cleaning up...
```
(They all install fine)

To get the environment variables working (Windows doesn't have the normal export things), i've added those to the config.py without their WILL_ prefix.

When starting will i get the following output:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\multiprocessing\forking.py", line 381, in main
    self = load(from_parent)
  File "C:\Python27\lib\pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "C:\Python27\lib\pickle.py", line 858, in load
    dispatch[key](self)
  File "C:\Python27\lib\pickle.py", line 1090, in load_global
    klass = self.find_class(module, name)
  File "C:\Python27\lib\pickle.py", line 1124, in find_class
    __import__(module)
ImportError: No module named keep_alive
Traceback (most recent call last):
  File "run_will.py", line 6, in <module>
    bot.bootstrap()
  File "C:\Python27\lib\site-packages\will\main.py", line 124, in bootstrap
    xmpp_thread.start()
  File "C:\Python27\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\Python27\lib\multiprocessing\forking.py", line 280, in __init__
    to_child.close()
IOError: [Errno 22] Invalid argument
```
I've been trying to figure out where this keep_alive module is located, but i can't seem to find it.
Any tips on where to find this?

**Comment by skoczen** [comment]
So the trouble here appears to be how windows does imports, and where will's looking for them. There's some deep and slightly dangerous magic happening in this part, and I'm not totally shocked there are windows installs where it's problematic.  

That said, I do know what we have folks successfully running will on windows.  Since you raised this about six months ago, and I'm just now replying, I'm not sure if you're available to help figure it out, but if so, please let me know!

**Comment by skoczen** [comment]
Closing this up since I haven't heard anything - please reopen if you're still seeing this!
