### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by Manasvibhatt297** [skoczen/will#262]
Please help me with this... I am facing this error while linking WILL with hipchat account

Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/manas/Will/local/lib/python2.7/site-packages/will/main.py", line 369, in bootstrap_bottle
    bottle.run(host='0.0.0.0', port=settings.HTTPSERVER_PORT, server='cherrypy', quiet=True)
  File "/home/manas/Will/local/lib/python2.7/site-packages/bottle.py", line 3114, in run
    server.run(app)
  File "/home/manas/Will/local/lib/python2.7/site-packages/bottle.py", line 2792, in run
    server.start()
  File "/home/manas/Will/local/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1955, in start
    raise socket.error(msg)
error: No socket could be created -- (('0.0.0.0', 80): [Errno 13] Permission denied)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/manas/Will/local/lib/python2.7/site-packages/will/decorators.py", line 27, in wrapped_f
    f(*args, **kwargs)
  File "/home/manas/Will/local/lib/python2.7/site-packages/will/decorators.py", line 104, in wrapped_f
    f(*args, **kwargs)
  File "/home/manas/Will/local/lib/python2.7/site-packages/will/plugins/admin/keep_alive.py", line 14, in ping_keep_alive
    requests.get("%s%s" % (settings.PUBLIC_URL, keep_alive_url))
  File "/home/manas/Will/local/lib/python2.7/site-packages/requests/api.py", line 59, in get
    return request('get', url, **kwargs)
  File "/home/manas/Will/local/lib/python2.7/site-packages/requests/api.py", line 48, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/manas/Will/local/lib/python2.7/site-packages/requests/sessions.py", line 451, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/manas/Will/local/lib/python2.7/site-packages/requests/sessions.py", line 557, in send
    r = adapter.send(request, **kwargs)
  File "/home/manas/Will/local/lib/python2.7/site-packages/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))

**Comment by skoczen** [comment]
@Manasvibhatt297 hey there!   First glance is that you're trying to run will on port 80, without permissions to do that. 

`error: No socket could be created -- (('0.0.0.0', 80): [Errno 13] Permission denied)`

Try either running him on a higher port (8000, etc), or running with `sudo` (I'd suggest a higher port, unless you have a specific reason to sudo!


Cheers,

-Steven

**Comment by Manasvibhatt297** [comment]
Now this pops up

Traceback (most recent call last):
  File "/home/manas/Will/local/lib/python2.7/site-packages/will/main.py", line 374, in bootstrap_xmpp
    self.start_xmpp_client()
  File "/home/manas/Will/local/lib/python2.7/site-packages/will/listener.py", line 16, in start_xmpp_client
    ClientXMPP.__init__(self, "%s/bot" % settings.USERNAME, settings.PASSWORD)
  File "/home/manas/Will/local/lib/python2.7/site-packages/sleekxmpp/clientxmpp.py", line 65, in __init__
    BaseXMPP.__init__(self, jid, 'jabber:client')
  File "/home/manas/Will/local/lib/python2.7/site-packages/sleekxmpp/basexmpp.py", line 70, in __init__
    self.requested_jid = JID(jid, cache_lock=True)
  File "/home/manas/Will/local/lib/python2.7/site-packages/sleekxmpp/jid.py", line 463, in __init__
    parsed_jid = _parse_jid(jid)
  File "/home/manas/Will/local/lib/python2.7/site-packages/sleekxmpp/jid.py", line 152, in _parse_jid
    domain = _validate_domain(domain)
  File "/home/manas/Will/local/lib/python2.7/site-packages/sleekxmpp/jid.py", line 233, in _validate_domain
    raise InvalidJID('Domain contains illegal characters')
InvalidJID: Domain contains illegal characters

**Comment by skoczen** [comment]
It's likely your username, password or hipchat settings aren't quite right - pay close attention to the steps required when setting up the first config: http://skoczen.github.io/will/#get-will-running-locally

**Comment by Manasvibhatt297** [comment]
if "HIPCHAT_SERVER" in settings:
        settings["USERNAME"] = "{user}@{host}".\
            format(user=settings["USERNAME"].split("@")[0],
                   host=settings["HIPCHAT_SERVER"])
    else:
        settings["HIPCHAT_SERVER"] = "api.hipchat.com"


Here I think I need to replace USERNAME to my hipchat account username. Please correct me if i m wrong.
but where to set the password in settings.py i only see

settings["PROXY_PASSWORD"] = parsed_proxy_url.password

I dont know what to do for password

**Comment by skoczen** [comment]
@Manasvibhatt297 please look closely at the instructions will gives when starting up - if you don't see them, you can see them in the screenshot from the [documentation](http://skoczen.github.io/will/#get-will-running-locally):

![uninitialized_env](https://cloud.githubusercontent.com/assets/200635/26677767/5a6d7c38-4721-11e7-9e65-74271c226b84.gif)

There's also explicit discussion of password and where to store credentials (environment variables - none of that stuff should live in `settings.py` in the docs as well: http://skoczen.github.io/will/config/

**Comment by Manasvibhatt297** [comment]
thanks i was ding the mistake in postactive file where instead of writing "username@chat.hipchat.com" I typed only "username". Thanks for your help

**Comment by Manasvibhatt297** [comment]
But will in not replying...

**Comment by skoczen** [comment]
@Manasvibhatt297 please track in #263 , I'm closing this issue up.
