### ISSUE TITLE
Will 2.0 fail when starting core processes

### ISSUE THREAD

**Issue by hcarlson1** [skoczen/will#328]
Hello, 
I am not experienced with python so I hope my issues is an easy fix. I am trying to get Will to interact with hipchat only. Will seems to fail when it starts core processes.  The only variables I have set in the config.py are: hipchat username, hipchat passwordhipchat v2 token, hipchat v1 token, redis url (loclahost to 6379), hipchat server. Please let me know if there are any other variables I need to set. 
 
Quick facts: 
OS: Windows 10
Python: 2.7
Redis: 3.2.1
Errors:
```
Bootstrapping complete.

Starting core processes:
  âo" IO: HipChat Backend started.
Thu, 21 Dec 2017 12:19:21 [CRITICAL] Error bootstrapping will.backends.analysis.nothing io:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\will\main.py", line 847, in bootstrap_analysis
    thread.start()
  File "C:\Python27\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\Python27\lib\multiprocessing\forking.py", line 277, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "C:\Python27\lib\multiprocessing\forking.py", line 199, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Python27\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 692, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 606, in save_list
    self._batch_appends(iter(obj))
  File "C:\Python27\lib\pickle.py", line 642, in _batch_appends
    save(tmp[0])
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 313, in save
    (t.__name__, obj))
PicklingError: Can't pickle '_subprocess_handle' object: <_subprocess_handle object at 0x00000000032D93D8>

Continuing...

Thu, 21 Dec 2017 12:19:22 [CRITICAL] Error bootstrapping will.backends.analysis.history io:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\will\main.py", line 847, in bootstrap_analysis
    thread.start()
  File "C:\Python27\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\Python27\lib\multiprocessing\forking.py", line 277, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "C:\Python27\lib\multiprocessing\forking.py", line 199, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Python27\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, T*rrv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.payc"e,back (most rece lnitn ec a6ll5 l5a,st) in save_:
dict
    self._batch_setitems(obj.iteritems())
  File "C:  File "<string>", line 1, in <module>
\  FilPe "yCth:o\Pnython27\lib\multiprocessing\forking.py", line 381, in main
27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self,     obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    selself = load(from_parent)
f._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 692, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 331, in sa v e
F i l e  self.sav"e_Cr:e\dPyucteh(obonj2=7o\blji, b*\rpvi)c
 k File l"e.pyC":,\ Plyithon2n7e\ 1l3i84b,\ piinc kloadl
e.py", l in e   425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 606, in save_list
    self._batch_appends(iter(obj))
  File "C:\Python27\lib\pickle.py", line 642, in _batch_appends
    save(tmp[0])
  File "C:\Python27\lib\pickle.py", line 331, irn save
    self.save_reduce(obj=obj, *rv)
eturn Unpickler(file)  File "C:\Python27\lib.\load()
pickle.py", line 425, in save_reduce
   File "C:\Python27\lib\pickle.py", line 864, in load
   save(state)
  Fil  e "C:\Pytho  n27\lib\pickle.py", line 286, in save
    dfispat(sech[lfke,y]( soelf)
bj) # Call unbound method with explicit self
  Fil e "C :F\ilPe "C:\Pyython27\litbhon2\7pickl\lieb.p\piy", line 655, in savec_dikle.py"c, line 8t86, in l
oad_eof
        self._batcrha_isseet EOFError
iteEmOsF(oEbrrojr.iterit
ems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 313, in save
    (t.__name__, obj))
PicklingError: Can't pickle '_subprocess_handle' object: <_subprocess_handle object at 0x00000000032D93D8>

Continuing...

Thu, 21 Dec 2017 12:19:24 [CRITICAL] Error bootstrapping will.backends.generation.fuzzy_all_matches io:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\will\main.py", line 876, in bootstrap_generation
    thread.start()
  File "C:\Python27\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\Python27\lib\multiprocessing\forking.py", line 277, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "C:\Python27\lib\multiprocessing\forking.py", line 199, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Python27\lib\pickle.py", line 224, in dump
    self.save(CoRITICAL:root:Error starting io adapter will.backends.io_adapters.hipchat:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\will\backends\io_adapters\base.py", line 114, in _start
    self.__event_listener_thread.start()
  File "C:\Python27\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  FbTijrl)aec
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py"C:\Pyte"b,ha ocln27\lib\muikltiprocesne 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
 s (i   self._batchng_setit\memofsst orrecent call(o kblast):
j.iiteritems())
  File "C:\Python27\lib\pickle.py", line 692, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.n pg y.py", line 277"F,,il e i "nlin<se t _r3_i3in1n,ig t>i__n",
sa  line 1, in <module>
   dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "C:\Python27\lib\multiprocessing\forking.py", line 199, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Python27\lib\pickle.py", v  elF
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\libii\pickle.pyln", line 425, in save e_re"edu Cc2:e
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) \24, in dPytho#un C27\lib\multiprocessing\forking.py", line 381, in main
mp
    self.save(obj)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Pythonall unbound method with exp 2l 7i \c litiselfb\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f( = load(from_parent)
self, obj) # Call unbound method with explicit self
  File "  Cs File ":eC\Pyl:\ftP
  Fiyhltonhon27\lib\pickle.py", line 1384, in load
e "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 286,     in save
    f(self, objr2)e7 t\luri#nb  UCanpickll\multiproceelsr(file) u.sinnlgbo\forkouinnagdd. (pm)ye
thod with explicit self
  File "C:\Python27\lib\pickle.py", line 606, in save_list
    self._batch_appends(iter(obj))
  File "C:\Python27\lib\pickle.py", line 642, in _batch_appends
    save(tmp[0])
  File "C:\Python27\  FilelT" ir,"Ca b:\l\cPipeython2bni7ae 67, cc\ikkln le (i.pmostbdispatcher
\y  pir "ce ,kc  lent call last):
lesi .pn eyeFl" 3f,i3. l1sle, inai  vn"se_rae 86<ev4sduce(obj=oe,tbj,r
 i  in *ng rv)
  File "C> ":sel\ , line 1Pyt,loh f.on27in <ms\lodaib\pduia
ckle>
le.  vp  Fildyeeis_r"paed tcu"Chc,:\e [Python27\key](self)
lib\mul  File "C:\Python27\lib\pickle.py", line 886,t(l ioproine 401, in save_reduce
    save(args)
  Ficiblenjessi "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  =n gobj, *rv)
  Fi\forking.pFilyllo"eead ",_ " eCC:\:liP\onytfePh
ython27\lib\pickle.py", line 554, in save_tuple
    save(element)
  File "C:\Python27\lib\pickle.py on"3 278 ,\1  l, li inrin abemis aie3\n
pickle. 3 p 1Ey , " OFErri,son er ll
if sEOna=FError loe
ve
    self.save_reduce(obj=obj, *rv)
  File "C:\Pythoa4nd22(57\, lfiirn obsm\a_pvpicarkeel_nert.p)
educe
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit y  "sF,ei llefl
  Fi"inCle:e \ 4P"2yC5, in save:t_\Prhoeytdn2uh7co\e
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, olnbi27\lib\pickle.py", line 655, in save_dbj\)ict
pi  c #k  l Call unbound metsehe.olpdfy"._bat ,cw hit_lhsetitems(obj.iti enexple ir138ci4it set, elimf
 sn ( Filel) ")oC:a\Py
 dt
File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 331, in save
  ho  self. n 2sa7 v\ e_rlreiedbtucu\ern(p oiUbcnjkl=peoi.bcpykj"l,,e *r rvl()if
el  e)F .l6io55al,de in()
 "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
 save_i dn File "C:\Pictpickle.py", l
 ye thon27\   self._batchlib\pickle.py2_", line 8648s, in load
6, in save
    f(self, obj) # Call unbo  und method with explicit self
  File "C:\Python27\lib\pickle.e py", titems(obj.iteritems())
 l  Fine 6idispatch[key](self)
le55,   in File  ""C:\PyCst:ave_dich\Pon27\lib\pickle.py", linytet
    h selo8fn27\._lib8bat\6ch_setitems(obj.itep,ritems in load_eof
())
  File "C:\Python27\lib\picki lcke   le.py", li.raise EOFError
py", line 687, in _batch_setitemsn
   Ee OFErr so6ave(v)
 r87, in _batch_setite
ms
    save(v)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    se lf._bFatile "Cc:\Pyht_shonetite27m\ls(obj.iibt\peickrilteems().py", )l
  File "C:\Python27\lib\ipincekl e.3py1"3,,  ilinn e 687, ins _ave
    (t.__name__, obj))b
PicklingError: Catch_setitems
  a  ns't pickave(v)
  File "C:\Python27\lilbe\p 'ickl_e.spyubp",r ocline 331, in save
e    self.save_reduce(obj=obj, *rv)
  File "sCs_handle:'\ oPython2b7jec\ltib\: <_spubpirocess_handle cobject at 0xk000000l0e0.py", line0 32D93D8>

C4on25, in save_reduce
  t inuing...

 save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
Thu, 21 Dec 2017 12:19:27 [CRITICAL] Error boo tstrap ping will.backends.genera tion.strict_regex io:

Traceback (most recent call last):
  File "C:\Pytho n27\lib\site-packages\will\main.py", line 876, in bootstrfap_generation
    thread.start()
  File "C:\Python27\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\Python27\lib\multiprocessing\forking.py", line 277, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "C:\Python27\lib\multiprocessing\forking.py", line 199, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Python27\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call uTnrbounda cmetehboadck  w(moitsh t erexcepnt lciaclitl  slaelstf
  File "C:\Pytho(sn27\lelib\picf)k:le
.py", line 655, in save_dict
    se , lfF .io_batch_setitems(obj.iteritems())
  File "C:\Python2le7bj\l) i "b#<\ spCtircalkle.py", line 687, ilin _batch_se utitnnegbm>ouns"d
    save(v)
  Fil me,  "C:\Pythlioenetn27ho\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method d 1 w,wi itin <mthoh exp expldliuicit secllieft>
  File "C:\Python27\lib\pickl
sel fe
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File F."ipC:y"\le "Pytho,C:\Pytho n27\lib\piline 655, in save_dictckln
 e2 .py", line 7 692, in _batch \_self._batlsetitemcib\s
h_ msetitems(obj.iteritems())
  File "C:\Python27\lib\picklu e.pl  save(v)
 ty"i File "C:\Python2,p7\r lib\picocesklsle.py", liing\forking.py", line 381, in main
ne 687, in _ ibatch_neset  3  31, in save
    seiself = load(from_parent)
tems
      save(v)Fl
  File "C:\Python27\lib\pifickle.py", lil.ne 286, in ssave_redaeuce(ov bj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\"eP
ib\pickle.py", line 2: 8\Python 627\lib\pick  f(lesel, in save
.py", line 1384, in load
    f(self, obj) # Call unbound method with explicit self
  File f , obj) # Call unbound"  method with C:\ eP xplicit self
 yr File "C:\Python27\lib\pickle.py"teturn Unp,hon27\lib\pickle.py", line 655, in save_dict
 l    self._batch_setitems(obj.iteritemiiscn(ke l))
  File "C:\Python27\lib\pickle.py", line 687,655, e ir(file).load()n _batch_setitems
i
n save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_seti  t    save(v)
Fe ile "C:\Python27\lib\pickle.py", line 864, in load
 File "C:\Python27\ ml  is
    save(v)
db ispatch[key](self)
 File \ "piC File "C:\Pyth:\Pytcon27khol\ne.py", line 282l6, in save
 7i \b\l pi icfbkle.p(\pickle.py"ys,"e ,llif,  line 88on6be, ij) # Call unbound n method w286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 754, in save_global
    (obj, module, name))
PicklingError: Can't pickle <function <lambda> at 0x0000000004C3D358>: it's not found as redis.client.<lambda>

 load_eof
ith explicit self
   Fil e  "C:\ Pythonrai27s\e EOlib\pFEricklre.py", olinre
606, in save_liEsOtFError
    self
._batch_appends(iter(obj))
  File "C:\Python27\lib\pickle.py", line 642, in _batch_appends
    save(tmp[0])
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 313, in save
    (t.__name__, obj))
PicklingError: Can't pickle '_subprocess_handle' object: <_subprocess_handle object at 0x00000000032D93D8>

Continuing...

Traceback (most recent call last):
  File "C:\Users\hcarlsoa\WillEnvironment\run_will.py", line 6, in <module>
    bot.bootstrap()
  File "C:\Python27\lib\site-packages\will\decorators.py", line 13, in wrapped_f
    return f(*args, **kwargs)
  File "C:\Python27\lib\site-packages\will\main.py", line 172, in bootstrap
    self.scheduler_thread.start()
  File "C:\Python27\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\Python27\lib\multiprocessing\forking.py", line 277, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "C:\Python27\lib\multiprocessing\forking.py", line 199, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Python27\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method Traceback (most recent call last):
w  File "<sitring>t", line 1, in <module>
h  File "C: \Python27\lib\multiprocessing\forking.py", line 381, in meaxiplincit
self
      File "C:\Python27\lsieblf \=p iclkoad(from_parent)
le.py", line 655, in save_dict
  File "C:\Python27\lib\pickle.py", line 1384, in load
        self._batch_setitems(objreturn Unpickler(file).load()
.iteritems())
  File "C:\Python27\lib\pickle.py", line 864, in load
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
        dispatch[key](self)
save(v)
  File "C:\Python27\lib\pickle.py", line 886, in load_eof
  File "C:\P  ython27\l ib\pickle.py", line 286, i n save
raise EOFError
    EOFErrorf(self, obj) # Call unbound method with explicit self

  File "C:\Python27\lib\multiprocessing\forking.py", line 67, in dispatcher
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 401, in save_reduce
    save(args)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 554, in save_tuple
    save(element)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
Traceback (most recent call last):
      File "<string>",f(self,  line 1, in <module>
obj) # Ca  File "C:\Python27\lib\multiprocessing\forking.py", line 381, in main
ll unbound method with explicit self
      File "C:\Python27\lib\picklself = load(from_e.pparent)
y", line 655  File "C:\Python27\lib\pickle.py", line 1384, in load
, in save_dict
        return Unpickler(file).load()
self._batch_setitems(obj.iteritems())
   F File "C:\Python27\lib\pickle.py", line 687, in _batch_setiile "C:\Pytems
thon27\lib\pickle.py", l    ine 864, in load
save(v)
dispatch[key](self)
  File "C:\Python27\lib\pickle.py", line 286, in save
  File     "C:\Python2f(self7\lib\pickle.py", line 886, in load_eof
, obj) # Call unbound method with explicit sel f
     File "C:\Python27\lib\pickle.py", line 606, in save_list
raise EOFError
    EOFErrorself._batch_appends(ite
r(obj))
  File "C:\Python27\lib\pickle.py", line 642, in _batch_appends
    save(tmp[0])
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 313, in save
    (t.__name__, obj))
pickle.PicklingError: Can't pickle '_subprocess_handle' object: <_subprocess_handle object at 0x00000000032D93D8>`
[willoutput.txt](https://github.com/skoczen/will/files/1587402/willoutput.txt)

```

**Comment by skoczen** [comment]
(Quick paste-on-all-open-issues update:)

**TL;DR**: New Will release EOM. Also, you're awesome.

**Full Update:** This may be TMI for you, and if so, cool, the thing you probably care about is above.  But given the total radio silence on my part - and the fact that I've always tried to create a community here where we got to be actual people instead of avatars and PRs, I wanted to give a bit more context.

As you may be aware from an earlier AFK, I got married in December, which was great, but burned the month from a Will perspective.  I planned to get back on it at the start of January, but instead found myself selling our house, and simultaneously hit with a surprisingly severe bout of depression.  The time since Jan 1 has been sort of a blur.  A dark blur, but a blur more than anything.   I saw the PRs and comments coming in, but didn't have the energy or time to do anything about them.

Things seem to be clearing up on both counts now, and I'm _really_ looking forward to getting these fixes in, catching up on bug reports, and being active in improving Will again. :)

With that, I'm aiming to get all outstanding PRs bundled into a release, and all issues replied to by the end of February.

Most of all, thanks for your contribution to Will, your patience with an imperfect, quite human project maintainer, and for continuing to come back, engage, and spend some of the precious seconds you get on earth making this project better.

I appreciate you.  Thank you.

**Comment by skoczen** [comment]
Hey @hcarlson1 , thanks for the report, and for your patience with my reply! 

So the error is that will isn't able to pickle up the subprocess module - which could be either a windows/python limitation, or a lower level requirement not installed.

If you're still poking at it, would you mind pasting the output of these two commands?

`pip freeze`

`python -V`

Thanks!

**Comment by wontonst** [comment]
Closing due to inactivity.
