### ISSUE TITLE
KeyError in will.main bootstrap_event_handler

### ISSUE THREAD

**Issue by wontonst** [skoczen/will#344]
Will 2.1.2, python 3.6.3.

```
Fri, 30 Mar 2018 10:00:54 [ERROR] Error handling message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/will/main.py", line 605, in bootstrap_event_handler
    q = analysis_threads[event.original_incoming_event_hash]
KeyError: '00f04bb65c242e552e2845c9584ae105'
Fri, 30 Mar 2018 10:00:54 [ERROR] Error handling message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/will/main.py", line 628, in bootstrap_event_handler
    q = generation_threads[event.original_incoming_event_hash]
KeyError: '00f04bb65c242e552e2845c9584ae105'
Fri, 30 Mar 2018 10:00:54 [ERROR] Error handling message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/will/main.py", line 605, in bootstrap_event_handler
    q = analysis_threads[event.original_incoming_event_hash]
KeyError: '00f04bb65c242e552e2845c9584ae105'
Fri, 30 Mar 2018 10:07:20 [ERROR] Error handling message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/will/main.py", line 605, in bootstrap_event_handler
    q = analysis_threads[event.original_incoming_event_hash]
KeyError: '2222133a0822e2468c40f3708f25c35f'
Fri, 30 Mar 2018 10:07:20 [ERROR] Error handling message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/will/main.py", line 605, in bootstrap_event_handler
    q = analysis_threads[event.original_incoming_event_hash]
KeyError: '2222133a0822e2468c40f3708f25c35f'
Fri, 30 Mar 2018 10:07:21 [ERROR] Error handling message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/will/main.py", line 605, in bootstrap_event_handler
    q = analysis_threads[event.original_incoming_event_hash]
KeyError: '2222133a0822e2468c40f3708f25c35f'
Fri, 30 Mar 2018 10:07:21 [ERROR] Error handling message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/will/main.py", line 605, in bootstrap_event_handler
    q = analysis_threads[event.original_incoming_event_hash]
KeyError: '2222133a0822e2468c40f3708f25c35f'
```

As far as I can tell, the errors do not seems to be impacting will.

**Comment by Chalta** [comment]
I see this too. Any ideas?

**Comment by Ashex** [comment]
This looks to be a transient error caused by race condition where Will consumes messages from the RTM and is trying to look up a message it hasn't cached yet.
