### ISSUE TITLE
Will fails to respond to a message when it first joins a new channel

### ISSUE THREAD

**Issue by Ashex** [skoczen/will#354]
The channel list doesn't include private channels will is not part of, therefore when will is added to a private channel it's unable to respond to messages until the channel list refreshes.  This is the exception thrown:

```
Wed, 23 May 2018 09:36:15 [CRITICAL] Error handling incoming event {u'source_team': u'T026PD3SL', u'text': u'<@UALU66Q7L> hello', u'ts': u'1527068175.000014', u'user': u'U39S9HZT5', u'team': u'T026PD3SL',
Traceback (most recent call last):
File "/opt/willbot/will/backends/io_adapters/base.py", line 43, in handle_incoming_event
m = self.normalize_incoming_event(event)
File "/opt/willbot/will/backends/io_adapters/slack.py", line 96, in normalize_incoming_event
channel = clean_for_pickling(self.channels[event["channel"]])
KeyError: u'GAKUU9WP3'
```

**Comment by wontonst** [comment]
Fixed in 2.1.3
