### ISSUE TITLE
AssertionError and crash when sending empty message to SLack

### ISSUE THREAD

**Issue by ezaitsev** [skoczen/will#360]
Noticed that invoking WillPlugin.say with a blank or empty message results in an AssertionError like below and also stopped Will from responding until a reboot. I think a quick fix is just to add
`if content == '': return`  
to https://github.com/skoczen/will/blob/master/will/plugin.py
at line 63

`Sat, 02 Jun 2018 11:45:36 [ERROR] Error sending to slack: no_text
Sat, 02 Jun 2018 11:45:36 [ERROR] {u'ok': False, u'error': u'no_text'}
Process Process-4:1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "venv/local/lib/python2.7/site-packages/will/backends/io_adapters/base.py", line 71, in __start_event_listeners
    self.handle_outgoing_event(pubsub_event.data)
  File "venv/local/lib/python2.7/site-packages/will/backends/io_adapters/slack.py", line 172, in handle_outgoing_event
    self.send_message(event)
  File "venv/local/lib/python2.7/site-packages/will/backends/io_adapters/slack.py", line 343, in send_message
    self.handle_request(r, data)
  File "venv/local/lib/python2.7/site-packages/will/backends/io_adapters/slack.py", line 217, in handle_request
    assert resp_json["ok"]
AssertionError`

**Comment by peterstarback** [comment]
@ezaitsev Thanks for the quick fix.  I too was having the same problem.  Any idea how to trace where empty messages originate?

**Comment by ezaitsev** [comment]
No I haven't been able to/had time to so far. Incidentally I did tweak my fix, and instead I am adding this to the beginning of the send_message function on line 299:

```
if event.content == '' or event.content == None:
            return
```
