### ISSUE TITLE
USERNAME KeyError when private Hipchat server is set

### ISSUE THREAD

**Issue by phiro69** [skoczen/will#364]
I'm going through the quickstart and ran into some trouble, I've isolated it down to when I add the WILL_HIPCHAT_SERVER (we run a private, internal hipchat server) env variable to my will.sh script:
```
<snip>
export WILL_HIPCHAT_SERVER=hipchat.ourcompany.com
export WILL_HIPCHAT_USERNAME=number_numberx3@chat.btf.hipchat.com
python run_will.py
```
This results in the following:
```
$ ./will.sh 
Traceback (most recent call last):
  File "run_will.py", line 2, in <module>
    from will.main import WillBot
  File "/home/me/willbot/lib/python3.6/site-packages/will/main.py", line 28, in <module>
    from will import settings
  File "/home/me/willbot/lib/python3.6/site-packages/will/settings.py", line 432, in <module>
    import_settings()
  File "/home/me/willbot/lib/python3.6/site-packages/will/settings.py", line 79, in import_settings
    format(user=settings["USERNAME"].split("@")[0],
KeyError: 'USERNAME'
$
```
Any ideas what I'm doing wrong? Is Python 3.6 OK to use?

**Comment by phiro69** [comment]
Also, for both python 2.7 and python 3.6, following the quickstart guide, when I configure it for just hipchat and no other backend (no slack, no rocketchat, no console), it puts the # on the wrong side of the quotes on the config.py, like this:

```
# Platforms and mediums messages can come in and go out on.
IO_BACKENDS = [
    "# will.backends.io_adapters.slack",
    "will.backends.io_adapters.hipchat",
    "# will.backends.io_adapters.rocketchat",
    "# will.backends.io_adapters.shell",
]
```

Which results in extra errors on startup :(

**Comment by skoczen** [comment]
@phiro69 thanks for the report - the latter bug will be fixed in the next release!

As for your first bug - yep, python 3.6 is fine - the problem is a missing setting.  You'll need to set a `WILL_USERNAME` as well for private hipchat instances.  Typically, this stuff is caught by the interactive startup script, but it looks like there are some snags in private hipchat.  I don't run one, so haven't been able to test it!

As you get it sorted, if you're up for putting together a PR that would make this easier for other folks, it'd be happily accepted!

**Comment by phiro69** [comment]
Found the debug settings in config.py, it's having issues getting to the jabber/xmpp id address. Picking at this...

**Comment by phiro69** [comment]
That was the issue, our private server may show your jabber id as @chat.btf.hipchat.com, but I was able to set it to @ourdomain.com and it was able to connect. It responded to a @name hi, so I should it down and I'm going to start molding Will to my nefarious needs ;)

What issue exactly were you inviting me to fix with a pr? The #'s on the inside of the quotes, or?
