### ISSUE TITLE
requests-2.18.4 requires urllib3<1.23.0

### ISSUE THREAD

**Issue by madstacks** [skoczen/will#366]
I just installed `will` in a fresh python3.4 virtualenv and it looks like the changes in 2.1.3 (cfea0f5f3c16) are pulling in `urllib3==1.23` which is not compatible with `requests==2.18.4`. 

```
$ generate_will_project
Traceback (most recent call last):
  File "/opt/venvs/will/lib/python3.4/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/opt/venvs/will/lib/python3.4/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/venvs/will/lib/python3.4/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.23 (/opt/venvs/will/lib/python3.4/site-packages), Requirement.parse('urllib3<1.23,>=1.21.1'), {'requests'})
```

In requests 2.19.x they are allowing `urllib3<1.24`
https://github.com/requests/requests/commit/ac944b7439009ffbf7a10dfee35202f1ac090e76#diff-2eeaed663bd0d25b7e608891384b7298

Do you recommend to upgrade requests to 2.19.x or downgrade urllib3 to 1.22?

**Comment by madstacks** [comment]
Thanks @skoczen. Also is there any reason to lock in on `pyasn1==0.1.7`? I am running into a conflict with the ldap3 package which requires `pyasn1>=0.1.8`.

**Comment by skoczen** [comment]
@madstacks nope, upgrading it's great.  If you don't mind, would you submit a PR with the requirements that all end up meshing for you?  Would be great to have a second set of eyes!

**Comment by madstacks** [comment]
I submitted a PR here https://github.com/skoczen/will/pull/367
