### ISSUE TITLE
Handle "connection timeout" in slack adapter

### ISSUE THREAD

**Issue by unicolet** [skoczen/will#388]
Almost every morning the bot goes offline, after the following gets logged:

```
Sep 21 11:33:23 pevm075 will.sh[21940]: Fri, 21 Sep 2018 11:33:23 [CRITICAL] Error in watching slack RTM:
Sep 21 11:33:23 pevm075 will.sh[21940]: Traceback (most recent call last):
Sep 21 11:33:23 pevm075 will.sh[21940]:   File "/opt/bot/chatbot/will/local/lib/python2.7/site-packages/will/backends/io_adapters/slack.py", line 545, in _watch_slack_rtm
Sep 21 11:33:23 pevm075 will.sh[21940]:     events = self.client.rtm_read()
Sep 21 11:33:23 pevm075 will.sh[21940]:   File "/opt/bot/chatbot/will/local/lib/python2.7/site-packages/slackclient/client.py", line 125, in rtm_read
Sep 21 11:33:23 pevm075 will.sh[21940]:     json_data = self.server.websocket_safe_read()
Sep 21 11:33:23 pevm075 will.sh[21940]:   File "/opt/bot/chatbot/will/local/lib/python2.7/site-packages/slackclient/server.py", line 255, in websocket_safe_read
Sep 21 11:33:23 pevm075 will.sh[21940]:     data += "{0}\n".format(self.websocket.recv())
Sep 21 11:33:23 pevm075 will.sh[21940]:   File "/opt/bot/chatbot/will/local/lib/python2.7/site-packages/websocket/_core.py", line 300, in recv
Sep 21 11:33:23 pevm075 will.sh[21940]:     opcode, data = self.recv_data()
Sep 21 11:33:23 pevm075 will.sh[21940]:   File "/opt/bot/chatbot/will/local/lib/python2.7/site-packages/websocket/_core.py", line 317, in recv_data
Sep 21 11:33:23 pevm075 will.sh[21940]:     opcode, frame = self.recv_data_frame(control_frame)
Sep 21 11:33:23 pevm075 will.sh[21940]:   File "/opt/bot/chatbot/will/local/lib/python2.7/site-packages/websocket/_core.py", line 330, in recv_data_frame
Sep 21 11:33:23 pevm075 will.sh[21940]:     frame = self.recv_frame()
Sep 21 11:33:23 pevm075 will.sh[21940]:   File "/opt/bot/chatbot/will/local/lib/python2.7/site-packages/websocket/_core.py", line 364, in recv_frame
Sep 21 11:33:23 pevm075 will.sh[21940]:     return self.frame_buffer.recv_frame()
Sep 21 11:33:23 pevm075 will.sh[21940]:   File "/opt/bot/chatbot/will/local/lib/python2.7/site-packages/websocket/_abnf.py", line 361, in recv_frame
Sep 21 11:33:23 pevm075 will.sh[21940]:     self.recv_header()
Sep 21 11:33:23 pevm075 will.sh[21940]:   File "/opt/bot/chatbot/will/local/lib/python2.7/site-packages/websocket/_abnf.py", line 309, in recv_header
Sep 21 11:33:23 pevm075 will.sh[21940]:     header = self.recv_strict(2)
Sep 21 11:33:23 pevm075 will.sh[21940]:   File "/opt/bot/chatbot/will/local/lib/python2.7/site-packages/websocket/_abnf.py", line 396, in recv_strict
Sep 21 11:33:23 pevm075 will.sh[21940]:     bytes_ = self.recv(min(16384, shortage))
Sep 21 11:33:23 pevm075 will.sh[21940]:   File "/opt/bot/chatbot/will/local/lib/python2.7/site-packages/websocket/_core.py", line 434, in _recv
Sep 21 11:33:23 pevm075 will.sh[21940]:     return recv(self.sock, bufsize)
Sep 21 11:33:23 pevm075 will.sh[21940]:   File "/opt/bot/chatbot/will/local/lib/python2.7/site-packages/websocket/_socket.py", line 81, in recv
Sep 21 11:33:23 pevm075 will.sh[21940]:     bytes_ = sock.recv(bufsize)
Sep 21 11:33:23 pevm075 will.sh[21940]:   File "/usr/lib/python2.7/ssl.py", line 756, in recv
Sep 21 11:33:23 pevm075 will.sh[21940]:     return self.read(buflen)
Sep 21 11:33:23 pevm075 will.sh[21940]:   File "/usr/lib/python2.7/ssl.py", line 643, in read
Sep 21 11:33:23 pevm075 will.sh[21940]:     v = self._sslobj.read(len)
Sep 21 11:33:23 pevm075 will.sh[21940]: error: [Errno 110] Connection timed out
```

@skoczen it seems it might be sufficient to handle the error in `_watch_slack_rtm`?

**Comment by fixedd** [comment]
Similar:

```
Error in watching slack RTM:
Traceback (most recent call last):
  File "/opt/crowdstrike/venvs/leoben/local/lib/python2.7/site-packages/will/backends/io_adapters/slack.py", line 458, in _watch_slack_rtm
    events = self.client.rtm_read()
  File "/opt/crowdstrike/venvs/leoben/local/lib/python2.7/site-packages/slackclient/client.py", line 235, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/opt/crowdstrike/venvs/leoben/local/lib/python2.7/site-packages/slackclient/server.py", line 296, in websocket_safe_read
    "Unable to send due to closed RTM websocket"
SlackConnectionError: Unable to send due to closed RTM websocket
```
