### ISSUE TITLE
ImportError in plugin leads to exception in error handling

### ISSUE THREAD

**Issue by wontonst** [skoczen/will#396]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/will/main.py", line 918, in bootstrap_plugins
    plugin_modules[full_module_name] = imp.load_source(module_name, module_path)
  File "/usr/local/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/plugins/orvibo_alert.py", line 5, in <module>
    from orvibo import Orvibo
ImportError: cannot import name 'Orvibo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run_will.py", line 6, in <module>
    bot.bootstrap()
  File "/usr/local/lib/python3.6/site-packages/will/decorators.py", line 13, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/will/main.py", line 134, in bootstrap
    self.bootstrap_plugins()
  File "/usr/local/lib/python3.6/site-packages/will/decorators.py", line 13, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/will/main.py", line 940, in bootstrap_plugins
    self.startup_error("Error loading %s" % (module_path,), e)
  File "/usr/local/lib/python3.6/site-packages/will/mixins/errors.py", line 20, in startup_error
    ":\n\n%s\nContinuing...\n" % traceback.format_exc(exception_instance)
  File "/usr/local/lib/python3.6/traceback.py", line 163, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/usr/local/lib/python3.6/traceback.py", line 117, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "/usr/local/lib/python3.6/traceback.py", line 497, in __init__
    capture_locals=capture_locals)
  File "/usr/local/lib/python3.6/traceback.py", line 332, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'ImportError' and 'int'

**Comment by rsalmond** [comment]
Hey @wontonst, can you confirm the orvibo module is present? What is the output of `pip freeze`.?

**Comment by rsalmond** [comment]
Also can you confirm that you have not accidentally created a file called `orvibo.py` in your plugin folder? If this is the case python will try to import `Orvibo` from your file rather than from the system module.

**Comment by wontonst** [comment]
There's no orvibo.py module. pip freeze shows orvibo present. The orvibo package does not have an Orvibo attribute. The expected outcome is an ImportError. The actual is an error during the error handling of the ImportError.
