### ISSUE TITLE
"Unable to remove task"

### ISSUE THREAD

**Issue by amckinley** [skoczen/will#56]
Intermittently, my will instance starts printing these errors every few minutes after starting up (and without any activity happening with my plugins).

```
CRITICAL Unable to remove task. Leaving it in, you'll have to clean it out by hand. Sorry!

Traceback (most recent call last):
  File "/home/austin/.virtualenvs/willbot/local/lib/python2.7/site-packages/will/scheduler.py", line 78, in _run_applicable_actions_in_list
    self.bot.remove_from_schedule(item["hash"], periodic_list=periodic_list)
  File "/home/austin/.virtualenvs/willbot/local/lib/python2.7/site-packages/will/mixins/schedule.py", line 81, in remove_from_schedule
    del sched_list[item_hash]
KeyError: -3340279509489936209

Continuing...

CRITICAL Unable to remove task. Leaving it in, you'll have to clean it out by hand. Sorry!

Traceback (most recent call last):
  File "/home/austin/.virtualenvs/willbot/local/lib/python2.7/site-packages/will/scheduler.py", line 78, in _run_applicable_actions_in_list
    self.bot.remove_from_schedule(item["hash"], periodic_list=periodic_list)
  File "/home/austin/.virtualenvs/willbot/local/lib/python2.7/site-packages/will/mixins/schedule.py", line 81, in remove_from_schedule
    del sched_list[item_hash]
KeyError: -1340245509339936023

Continuing...

CRITICAL Unable to remove task. Leaving it in, you'll have to clean it out by hand. Sorry!

Traceback (most recent call last):
  File "/home/austin/.virtualenvs/willbot/local/lib/python2.7/site-packages/will/scheduler.py", line 78, in _run_applicable_actions_in_list
    self.bot.remove_from_schedule(item["hash"], periodic_list=periodic_list)
  File "/home/austin/.virtualenvs/willbot/local/lib/python2.7/site-packages/will/mixins/schedule.py", line 81, in remove_from_schedule
    del sched_list[item_hash]
KeyError: -8340306509534935736

Continuing...
```

**Comment by skoczen** [comment]
Closing this, as it's older than some nice bottles of wine I own.  Please re-open if it's still an issue!
