### ISSUE TITLE
image me fails frequently (suspected throttling on google end)

### ISSUE THREAD

**Issue by rustyrazorblade** [skoczen/will#68]
I get this quite a bit:

```
Traceback (most recent call last):
  File "/home/meatbot/.virtualenvs/meatbot/local/lib/python2.7/site-packages/will/listener.py", line 148, in fn
    listener["fn"](*args, **kwargs)
  File "/home/meatbot/.virtualenvs/meatbot/local/lib/python2.7/site-packages/will/decorators.py", line 6, in wrapped_f
    f(*args, **kwargs)
  File "/home/meatbot/.virtualenvs/meatbot/local/lib/python2.7/site-packages/will/plugins/productivity/images.py", line 19, in image_me
    results = r.json()["responseData"]["results"]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

But google image search does return images.  This has been happening with the search term "jim webber" today, with `will==0.5.7`

Is it possible my bot is being throttled?

**Comment by skoczen** [comment]
This hasn't shown up for me in a few months.  Closing - please reopen if you still see it!
