### ISSUE TITLE
Unable to save / Major startup failure.

### ISSUE THREAD

**Issue by creack** [skoczen/will#72]
When I try to run will, I hit a ton of exceptions. All related I think.

Context: Trying to run will locally. Redis up and running & accessible. Brand new python2.7 install.

Will install process:

```
# brand new environment with python2.7 freshly installed.
cd /will
pip install -r requirements.txt
pip install will
generate_will_project
# export env
./run_will.py
```

```
Starting core processes:
  ✓ Web server started.
CRITICAL Unable to save plugin_modules_library:
Traceback (most recent call last):
  File "/src/will/mixins/storage.py", line 37, in save
    ret = self.storage.set(key, pickle.dumps(value))
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 1055, in set
    return self.execute_command('SET', *pieces)
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 562, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 874, in get_connection
    connection = self.make_connection()
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 883, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 393, in __init__
    self.port = int(port)
TypeError: int() argument must be a string or a number, not 'NoneType'

.... (A lot like that)

CRITICAL Unable to save will_periodic_times_list:
Traceback (most recent call last):
  File "/src/will/mixins/storage.py", line 37, in save
    ret = self.storage.set(key, pickle.dumps(value))
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 1055, in set
    return self.execute_command('SET', *pieces)
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 562, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 874, in get_connection
    connection = self.make_connection()
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 881, in make_connection
    raise ConnectionError("Too many connections")
ConnectionError: Too many connections

... (A lot again)
```

Then next section:

```
  ✓ Scheduler started.
WARNING  Unable to load last_random_schedule
CRITICAL Unable to save last_random_schedule:
Traceback (most recent call last):
  File "/src/will/mixins/storage.py", line 37, in save
    ret = self.storage.set(key, pickle.dumps(value))
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 1055, in set
    return self.execute_command('SET', *pieces)
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 562, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 874, in get_connection
    connection = self.make_connection()
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 881, in make_connection
    raise ConnectionError("Too many connections")
ConnectionError: Too many connections
```

Then it is basically an infinite loop of exceptions. When interrupting:

```
WARNING  Unable to load will_schedule_times_list
WARNING  Unable to load will_periodic_times_list
CRITICAL Unable to save scheduler_lock:
Traceback (most recent call last):
  File "/src/will/mixins/storage.py", line 37, in save
    ret = self.storage.set(key, pickle.dumps(value))
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 1055, in set
    return self.execute_command('SET', *pieces)
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 562, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 874, in get_connection
    connection = self.make_connection()
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 881, in make_connection
    raise ConnectionError("Too many connections")
ConnectionError: Too many connections

^CKeyboardInterrupt
KeyboardInterrupt
  ✓ Chat client started.
  ✓ Will is running.
KeyboardInterrupt
DEBUG    Starting HANDLER THREAD


Received keyboard interrupt, quitting threads..Exception KeyError: KeyError(139970250096720,) in <module 'threading' from '/usr/local/lib/python2.7/threading.pyc'> ignored
```

**Comment by skoczen** [comment]
Update on this - better error handling code for redis urls is going in to the next release, which I hope to have out today.

On your 1) and 2), I don't actually have a better solution.

Simply blowing up and quitting will would fit the bill for your 1)  (#2 is actually handled - it's the error you copy/pasted), but it also means that will would die anytime a redis backend went down, there was a network problem, etc. - and he wouldn't come back up until explicitly restarted.

For the case where a user has the format or content of their redis url wrong, I believe the current behavior to complain loudly and often in logs is the best solution.  The developer should be able to see that the url is wrong, and then get it fixed. 

If you have a cleaner solution, please reopen - I'm all ears!

**Comment by odedpr** [comment]
I also had this issue 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sleekxmpp/xmlstream/resolver.py", line 242, in get_AAAA
    recs = resolver.query(host, dns.rdatatype.AAAA)
  File "/usr/local/lib/python2.7/site-packages/dns/resolver.py", line 824, in query
    raise NoNameservers
NoNameservers
ERROR

i worked around it by passing docker with --dns flag ( 8.8.8.8 )
