### ISSUE TITLE
Will throwing exception & exiting chat - missing user information

### ISSUE THREAD

**Issue by rustyrazorblade** [skoczen/will#75]
I've seen this issue since I first started using Will about 3 months ago. 

```
KeyError: u'1344989'
ERROR    Error processing event handler: <bound method WillBot.join_rooms of <will.main.WillBot object at 0x7fba76674c50>>
Traceback (most recent call last):
  File "/home/meatbot/.virtualenvs/meatbot/local/lib/python2.7/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1699, in _event_runner
    func(*args)
  File "/home/meatbot/.virtualenvs/meatbot/local/lib/python2.7/site-packages/will/listener.py", line 55, in join_rooms
    self.update_will_roster_and_rooms()
  File "/home/meatbot/.virtualenvs/meatbot/local/lib/python2.7/site-packages/will/listener.py", line 85, in update_will_roster_and_rooms
    user_data = self.full_hipchat_user_list[hipchat_id]
KeyError: u'1344989'
ERROR    Error handling {jabber:client}iq stanza
Traceback (most recent call last):
  File "/home/meatbot/.virtualenvs/meatbot/local/lib/python2.7/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1699, in _event_runner
    func(*args)
  File "/home/meatbot/.virtualenvs/meatbot/local/lib/python2.7/site-packages/will/listener.py", line 55, in join_rooms
    self.update_will_roster_and_rooms()
  File "/home/meatbot/.virtualenvs/meatbot/local/lib/python2.7/site-packages/will/listener.py", line 85, in update_will_roster_and_rooms
    user_data = self.full_hipchat_user_list[hipchat_id]
KeyError: u'1344989'
ERROR    u'1344989'
Traceback (most recent call last):
  File "/home/meatbot/.virtualenvs/meatbot/local/lib/python2.7/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1699, in _event_runner
    func(*args)
  File "/home/meatbot/.virtualenvs/meatbot/local/lib/python2.7/site-packages/will/listener.py", line 55, in join_rooms
    self.update_will_roster_and_rooms()
  File "/home/meatbot/.virtualenvs/meatbot/local/lib/python2.7/site-packages/will/listener.py", line 85, in update_will_roster_and_rooms
    user_data = self.full_hipchat_user_list[hipchat_id]
KeyError: u'1344989'
```

**Comment by skoczen** [comment]
Haven't seen this in a few months - closing this up. Please reopen if folks are still seeing this!

**Comment by camilian** [comment]
I am seeing this using latest version.  Errors out every other day or so.
